version: '3.9'
services:
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password --sync_binlog=0 --innodb_doublewrite=OFF  --innodb-flush-log-at-trx-commit=0 --innodb-flush-method=nosync
    restart: always
    env_file: .env
    ports:
      - '$DB_PORT:3306'
    volumes:
      - mysql_data:/var/lib/mysql
  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8080:80
    environment:
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: $MYSQL_ROOT_PASSWORD
  # api:
  #   build:
  #     dockerfile: Dockerfile.dev # Use dev dockerfile in server folder
  #     context: ./
  #   volumes:
  #     - /app/node_modules # Copy node_modules folder as is
  #     - ./:/app     # Copy rest of / folder to /app
  #   ports:
  #     - '3000:3000'
volumes:
  mysql_data:
    driver_opts:
      type: tmpfs
      device: tmpfs